Leaderboard v3
emojirades/emojirades pull request #194
Opened 2020-09-10 01:15 UTC by phelios

Updates:

- Gone a little wild with refactoring 😬 
- Add titles to leaderboards
- Default leaderboard to weekly

![image](https://user-images.githubusercontent.com/997870/92670209-de44a880-f356-11ea-975e-5272211a99ca.png)

2020-09-10 10:08 UTC, michael-robbins requested changes
Thoughts on the alltime? I'm 100% fine with the rest though, lookin pretty 🔥

2020-09-10 10:08 UTC, michael-robbins commented on emojirades/commands/scorekeeper_commands/leaderboard_command.py
> +        r"<@{me}> (score|leader)[\s]*board (?P<range>weekly|monthly|alltime)",
I kinda like 'all time' as 'alltime' seems a bit weird, as it's not a single word? Can we cater for both?

2020-09-10 10:08 UTC, michael-robbins commented on emojirades/commands/scorekeeper_commands/leaderboard_command.py
> +        # TODO: :thinking: Maybe we could add default value regex in the command translation
That sounds too crazy, I like this way!

2020-09-10 10:08 UTC, michael-robbins commented on emojirades/commands/scorekeeper_commands/leaderboard_command.py
> +        if self.time_unit == TimeRange.ALLTIME:
Same deal here TimeRange.ALL_TIME sounds better to me, thoughts?

2020-09-10 10:08 UTC, michael-robbins commented on emojirades/printers/leaderboard_printer.py
> +        lines = ["```", f" :: {self.time_unit.capitalize()} leaderboard ::", ""]
And if Alltime as printed here, it'd be `All Time`?

2020-09-10 10:21 UTC, phelios commented
@michael-robbins totally with you on this. I was on the fence about reverting it back to "overall". I just don't have something to compare to. But Happy with ALL_TIME and "All Time". Will fix that tomorrow, not on my workstation anymore :)

2020-09-11 00:03 UTC, michael-robbins approved these changes

2020-09-11 00:38 UTC, merged