Leaderboard v4
emojirades/emojirades pull request #199
Opened 2020-09-22 01:50 UTC by phelios

- Add date range into title printing
- Allow date mocking through env
- Allow users to specify a date when requesting for weekly and monthly leaderboards

2020-09-22 01:55 UTC, phelios commented
wooh.. first PR with green build on first try! Made sure I used double quotes too ;)

2020-09-22 03:53 UTC, michael-robbins commented
Deserves an instant approve just for that alone lol

2020-09-22 04:00 UTC, michael-robbins requested changes

2020-09-22 04:51 UTC, phelios commented on emojirades/analytics/leaderboard.py
> +    def get_by_range(self, of_date: pendulum.DateTime, time_unit):
yeah man, seriously the "optional typing" is throwing me off coz I'm lazy lol. It's now typed to the TimeRange constants, which should be enums, so I'll change that.

2020-09-22 04:53 UTC, phelios commented on emojirades/commands/scorekeeper_commands/leaderboard_command.py
> +            mock_date = os.environ.get("EMOJIRADE_MOCK_DATE")
heheh.. can it? 😬  Behave is using it to get a consistent leaderboard output.

2020-09-22 04:55 UTC, phelios commented on emojirades/printers/leaderboard_printer.py
> +        title.append("::")
I though it's easier to look at this way. Also coz I'll have to handle the extra space in ALL TIME leaderboard where there's no date range.

2020-09-22 05:22 UTC, phelios commented on emojirades/commands/scorekeeper_commands/leaderboard_command.py
> +                self.logger.info(f"Mocking date to: {of_date}")
hmm.. there's an of_date that's set to `now()` at the top of the method. I see why this is not very clear, but the alternative is moving it down here as else statement but would look weird too for the printer coz it's not part of the if-else. Any better idea?

2020-10-08 22:50 UTC, michael-robbins commented on emojirades/commands/scorekeeper_commands/leaderboard_command.py
> +                self.logger.info(f"Mocking date to: {of_date}")
Sorry missed that, yep that's fine!

2020-10-08 22:50 UTC, michael-robbins approved these changes

2020-10-08 23:07 UTC, michael-robbins approved these changes

2020-10-09 00:09 UTC, merged